### PR TITLE
README updated with improved instructions for accessing recovery.

### PR DESCRIPTION
**Pull request by dumol**
Hi again!

Had struggle a bit to access recovery in this setup, so I tried to improve the README with my finds.

Thanks!

### CODE REVIEW

**Comment by nieder** [comment]
Shouldn't that last step be running `./boot.efi` instead of plain `boot.efi` ?

**Comment by dumol** [comment]
Have double-checked on a 10.15 Catalina VM… It's not needed to put `./` in front of `boot.efi` to start it, but I guess it doesn't hurt, so I'll add it back. 

Also maybe clarify a bit the drive changing part, as I still got a bit confused, even with my updated instructions.

**Comment by dumol** [comment]
Actually, if I try `./boot.efi` (in the right dir) it's not booting, I get: _'./boot.efi' is not recognized as an internal or external command, operable program, or script file._

For me, it only works without `./` in front of `boot.efi`.

**Comment by jeff-h** [comment]
Thanks for working on this — I find the original quite confusing. Indeed even in your updated version I am struggling; <kbd>CMD</kbd>+<kbd>C</kbd> is mapped in my VirtualBox to "scaled mode". Why is this not the case in your VirtualBox?

**Comment by dumol** [comment]
Thanks for the feedback! Can't help you with `CMD`+`C` though as:

  1. It is possible that I have changed the hot key in VirtualBox on macOS, to free `CMD`, but…
  2. I can't check, as I have migrated that Mac mini to Linux. Now I don't even run the graphical Qt-based VirtualBox manager, I use phpVirtualBox.

**Pull request merged**
